# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://blog.thibmaekelbergh.be
enforce_ssl: blog.thibmaekelbergh.be
permalink: :title

# THEME-SPECIFIC CONFIGURATION
theme:
  title: Thibault Maekelbergh
  avatar: avatar.jpg
  description: "A nice blog about development, Raspberry Pi and OS X"

  header_text: >
     <p>A collection of blog posts varying from things I achieved to weekend projects to stuff I designed and coded or just an article reflecting my views and opinions.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: true
  email_address: "thibault.maekelbergh@icloud.com"
  behance: "thibmaek"
  dribbble: "thibmaek"
  instagram: "thibmaekelbergh"
  github: "thibmaek"
  linkedin: "https://www.linkedin.com/profile/view?id=343554566&trk=nav_responsive_tab_profile_pic"
  tumblr: "betypo"
  twitter: "thibmaekelbergh"

  # Scripts
  disqus_shortname: "thibaultmaekelbergh"
  katex: false

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

# PAGINATION
paginate: 7
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
gems:
  - jekyll-paginate
  - jekyll-gist
exclude: ["vendor"]
