# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Thibault Maekelbergh
  avatar: avatar.jpg
  description: "A nice blog about development, raspberry pi and os x" # used by search engines

  # Header and footer text
  header_text: >
     <p>A collection of blog posts varying from things I achieved to weekend projects to stuff I designed and coded or just an article reflecting my views and opinions.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: true
  email_address: "thibault.maekelbergh@icloud.com"
  behance: "thibmaek"
  github: "thibmaek"
  linkedin: "https://www.linkedin.com/profile/view?id=343554566&trk=nav_responsive_tab_profile_pic"
  tumblr: "betypo"
  twitter: "thibmaekelbergh"

  # Scripts
  google_analytics: "UA-54288425-1"
  disqus_shortname: "thibmaekblog"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
