version: '3'

services:
  gatsby:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app