version: '2.1'

services:
  blog.thibmaekelbergh.be:
    image: blog.thibmaekelbergh.be
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js